{{- if .Values.keda.enabled }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include "erpnext.fullname" . }}-worker-d
  labels:
    {{- include "erpnext.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    name: {{ include "erpnext.fullname" . }}-worker-d
  pollingInterval: 15
  cooldownPeriod: 300
  minReplicaCount: {{ .Values.keda.workerD.minReplicas | default 1 }}
  maxReplicaCount: {{ .Values.keda.workerD.maxReplicas | default 3 }}
  triggers:
    - type: redis
      metadata:
        address: {{ include "erpnext.fullname" . }}-redis-queue-master.{{ .Release.Namespace }}.svc.cluster.local:6379
        listName: "default"
        listLength: {{ .Values.keda.workerD.queueThreshold | default "5" | quote }}
        activationListLength: "1"
{{- end }}
