apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "erpnext.fullname" . }}-worker-d
  labels:
    {{- include "erpnext.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "erpnext.name" . }}-worker-d
      app.kubernetes.io/instance: {{ .Release.Name }}-worker-d
