apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: erpnext
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/juuja-ali/shaafi.git
    targetRevision: HEAD
    path: erpnext-gitops/environments/erpnext
  destination:
    server: https://kubernetes.default.svc
    namespace: erpnext
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true
